name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17', '21', '24' ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven on JDK ${{ matrix.java-version }}
      run: |
        mvn -B -ntp -f pom.xml package
        mvn -B -ntp -f examples/simple/pom.xml compiler:compile
        mvn -B -ntp -f examples/irrelevant/pom.xml compiler:compile
