name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Set release version
        run: |
          mvn -B -ntp -f pom.xml versions:set -DnewVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
          mvn -B -ntp -f core/pom.xml versions:set -DnewVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
          mvn -B -ntp -f maven-plugin/pom.xml versions:set -DnewVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
          for dir in examples/*/; do
            echo "Updating $dir"
            mvn -B -ntp -f "$dir/pom.xml" versions:set-property -Dproperty=nullaudit.version -DnewVersion=${{ github.event.inputs.version }} -DgenerateBackupPoms=false
          done
          sed -i '/<version>/s/>.*</>${{ github.event.inputs.version }}</' README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'Prepare release ${{ github.event.inputs.version }}'
          body: 'Automated preparation of ${{ github.event.inputs.version }} release'
          commit-message: 'Set version to ${{ github.event.inputs.version }}'
          branch: 'release-${{ github.event.inputs.version }}'
